---
- name: Run the playbook tasks on the localhost from the ~/vagrant folder
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    groupname: 52pickup
    username: 52pickup

  tasks:
    - name: Create group
      ansible.builtin.group:
        name: "{{ groupname }}"
        state: present

    - name: Ensure 52pickup user is present
      ansible.builtin.user:
        name: "{{ username }}"
        groups: "{{ groupname }},sudo"
        password: "$1$XF.06J/n$A1G6zX5AF33pQQOTcH0Ix."
        shell: /bin/bash
        state: present

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present
        update_cache: yes

    # - name: Add Docker GPG key
    #   ansible.builtin.shell: |
    #     curl -fsSL https://download.docker.com/linux/ubuntu/dists/jammy/Release.gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    #   args:
    #     executable: /bin/bash
    #   become: yes

    # - name: Add Docker repository (Ubuntu 22.04 repo for compatibility)
    #   ansible.builtin.shell: |
    #     echo "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu/ stable" | sudo tee /etc/apt/sources.list.d/docker.list
    #   args:
    #     executable: /bin/bash
    #   become: yes

    # - name: Install Docker Engine
    #   ansible.builtin.apt:
    #     update_cache: yes
    #     name:
    #       - docker-ce
    #       - docker-ce-cli
    #       - containerd.io
    #     state: present

    # - name: Start and enable Docker service
    #   ansible.builtin.systemd:
    #     name: docker
    #     enabled: yes
    #     state: started

    - name: Install additional packages
      ansible.builtin.apt:
        name:
          - nginx
          - vim
          - curl
          - unzip
          - php-fpm
          - nano
          - python3
          - python3-pip
          - firefox
          - gnome-shell-extensions
          - python-is-python3
          - openjdk-17-jre
        state: present

    - name: Install Python Docker module
      ansible.builtin.pip:
        name: docker
        executable: /usr/bin/pip3

    # - name: Create cli-plugins folder for docker-compose
    #   ansible.builtin.file:
    #     path: /usr/local/lib/docker/cli-plugins
    #     state: directory

    # - name: Download and install docker-compose
    #   ansible.builtin.get_url:
    #     url: https://github.com/docker/compose/releases/download/v2.9.0/docker-compose-linux-aarch64
    #     dest: /usr/local/lib/docker/cli-plugins/docker-compose
    #     mode: "0755"

    # - name: Install compose-switch for Docker 1.x support
    #   ansible.builtin.get_url:
    #     url: https://github.com/docker/compose-switch/releases/download/v1.0.5/docker-compose-linux-aarch64
    #     dest: /usr/local/bin/compose-switch
    #     mode: "0755"
